import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";
import { TestExecutor } from "../src/ai/executor.js";
import { TestEvaluator } from "../src/ai/evaluator.js";
import { normalizeFindings } from "../src/findings/normalizer.js";
import { AttackAnalyzer } from "../src/findings/attack.analyzer.js";
import { CORPUS, startCorpusServer, type CorpusCase } from "./corpus/targets.js";
import type { ExecutionContext } from "../src/orchestrator/context.js";

/**
 * PRECISION MEASUREMENT
 *
 * Runs the full detection pipeline against a corpus with known ground truth and
 * asserts hard thresholds. The numbers this produces are the ones published in
 * the README, and they are regenerated by CI on every run so they cannot drift
 * away from reality.
 *
 * Precision is gated harder than recall on purpose. A missed finding is a bug.
 * A false positive that blocks a good deploy gets the tool uninstalled.
 */

interface Outcome {
  case: CorpusCase;
  flaggedConfirmed: boolean;
  proofs: string[];
  reportedCategory?: string;
}

const analyzer = new AttackAnalyzer();

describe("Detection precision against the corpus", () => {
  let baseUrl: string;
  let close: () => Promise<void>;
  let outcomes: Outcome[] = [];

  beforeAll(async () => {
    const server = await startCorpusServer();
    baseUrl = server.baseUrl;
    close = server.close;

    const ctx = {
      targetUrl: baseUrl,
      environment: { baseUrl, images: [], services: [], managedByUs: false },
      auth: { type: "none", role: "anonymous" },
      config: { failOnSeverity: "HIGH", safety: {} },
    } as unknown as ExecutionContext;

    const testCases = CORPUS.map((c) => ({
      name: c.id,
      endpoint: `${c.request.method} ${c.request.path.split("?")[0]}`,
      category: c.category,
      description: c.description,
      request: c.request,
      expectedVulnerable: c.expectedVulnerable,
    }));

    const executed = await new TestExecutor(ctx).execute(testCases, 4);
    const raws = await new TestEvaluator(ctx).evaluate(executed.results);

    outcomes = CORPUS.map((corpusCase) => {
      const result = executed.results.find((r) => r.testCase.name === corpusCase.id);
      const finding = raws.find((r) => r.description.startsWith(`${corpusCase.id}:`));

      return {
        case: corpusCase,
        flaggedConfirmed: (result?.proofs.length ?? 0) > 0,
        proofs: result?.proofs ?? [],
        reportedCategory: finding?.category,
      };
    });
  });

  afterAll(async () => {
    await close?.();
  });

  it("flags every genuinely vulnerable endpoint", () => {
    const missed = outcomes.filter((o) => o.case.vulnerable && !o.flaggedConfirmed);
    expect(missed.map((m) => m.case.id)).toEqual([]);
  });

  it("flags no clean endpoint as a confirmed exploit", () => {
    const falsePositives = outcomes.filter((o) => !o.case.vulnerable && o.flaggedConfirmed);
    expect(falsePositives.map((f) => `${f.case.id} (proofs: ${f.proofs.join(", ")})`)).toEqual([]);
  });

  it("meets the published precision and recall thresholds", () => {
    const tp = outcomes.filter((o) => o.case.vulnerable && o.flaggedConfirmed).length;
    const fp = outcomes.filter((o) => !o.case.vulnerable && o.flaggedConfirmed).length;
    const fn = outcomes.filter((o) => o.case.vulnerable && !o.flaggedConfirmed).length;
    const tn = outcomes.filter((o) => !o.case.vulnerable && !o.flaggedConfirmed).length;

    const precision = tp + fp === 0 ? 1 : tp / (tp + fp);
    const recall = tp + fn === 0 ? 1 : tp / (tp + fn);
    const f1 = precision + recall === 0 ? 0 : (2 * precision * recall) / (precision + recall);

    const report = {
      generatedAt: new Date().toISOString(),
      corpusSize: CORPUS.length,
      vulnerableCases: CORPUS.filter((c) => c.vulnerable).length,
      cleanCases: CORPUS.filter((c) => !c.vulnerable).length,
      truePositives: tp,
      falsePositives: fp,
      trueNegatives: tn,
      falseNegatives: fn,
      precision: Number(precision.toFixed(4)),
      recall: Number(recall.toFixed(4)),
      f1: Number(f1.toFixed(4)),
      perCase: outcomes.map((o) => ({
        id: o.case.id,
        groundTruth: o.case.vulnerable ? "vulnerable" : "clean",
        flaggedConfirmed: o.flaggedConfirmed,
        proofs: o.proofs,
        reportedCategory: o.reportedCategory,
      })),
    };

    const outPath = resolve(process.cwd(), "security-reports/precision.json");
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, JSON.stringify(report, null, 2));

    console.log(
      `\n  Precision ${(precision * 100).toFixed(1)}%  Recall ${(recall * 100).toFixed(1)}%  F1 ${(f1 * 100).toFixed(1)}%` +
        `  (TP ${tp} FP ${fp} TN ${tn} FN ${fn})\n`
    );

    // A false positive gets the tool deleted from the pipeline. Zero tolerance.
    expect(precision).toBe(1);
    expect(recall).toBeGreaterThanOrEqual(0.9);
  });

  it("reports the category that matches the proof, not the test's label", () => {
    // The SQLi test case and the clean parameterised case carry the same
    // category label. Only the one with a real database error may be reported.
    const cleanQuery = outcomes.find((o) => o.case.id === "clean-parameterised");
    expect(cleanQuery?.reportedCategory).toBeUndefined();

    const traversal = outcomes.find((o) => o.case.id === "vuln-traversal");
    expect(traversal?.reportedCategory).toBe("Path Traversal");

    const ssrf = outcomes.find((o) => o.case.id === "vuln-ssrf");
    expect(ssrf?.reportedCategory).toBe("Server-Side Request Forgery (SSRF)");
  });

  it("produces a SAFE verdict for the clean half of the corpus in isolation", async () => {
    const ctx = {
      targetUrl: baseUrl,
      environment: { baseUrl, images: [], services: [], managedByUs: false },
      auth: { type: "none", role: "anonymous" },
      config: { failOnSeverity: "HIGH", safety: {} },
    } as unknown as ExecutionContext;

    const cleanCases = CORPUS.filter((c) => !c.vulnerable).map((c) => ({
      name: c.id,
      endpoint: `${c.request.method} ${c.request.path.split("?")[0]}`,
      category: c.category,
      description: c.description,
      request: c.request,
      expectedVulnerable: c.expectedVulnerable,
    }));

    const executed = await new TestExecutor(ctx).execute(cleanCases, 4);
    const raws = await new TestEvaluator(ctx).evaluate(executed.results);
    const verdict = analyzer.generateVerdict(normalizeFindings(raws));

    expect(verdict.confirmedExploits).toHaveLength(0);
    expect(verdict.verdict).toBe("SAFE");
  });
});
