import { GitHubNotificationConfig } from "../core/config.loader.js";
import { SecurityVerdict } from "../findings/attack.analyzer.js";
import { Finding } from "../findings/finding.js";

const ISSUE_LABEL = "breach-gate";
const ISSUE_TITLE_PREFIX = "[Breach Gate]";

export async function sendGitHubNotification(
  config: GitHubNotificationConfig,
  verdict: SecurityVerdict,
  findings: Finding[],
  targetUrl: string
): Promise<void> {
  const prNumber = process.env["GITHUB_PR_NUMBER"];

  if (config.prComment && prNumber) {
    await postPrComment(config, verdict, findings, targetUrl, prNumber);
  }

  if (config.issueOnFailure && (verdict.verdict === "UNSAFE" || verdict.verdict === "INCONCLUSIVE")) {
    await upsertIssue(config, verdict, findings, targetUrl);
  }
}

async function postPrComment(
  config: GitHubNotificationConfig,
  verdict: SecurityVerdict,
  findings: Finding[],
  targetUrl: string,
  prNumber: string
): Promise<void> {
  const body = buildReportBody(verdict, findings, targetUrl);
  const url = `https://api.github.com/repos/${config.repo}/issues/${prNumber}/comments`;

  const response = await ghFetch(url, config.token, "POST", { body });
  if (!response.ok) {
    throw new Error(`GitHub PR comment failed (${response.status}): ${await response.text()}`);
  }
}

async function upsertIssue(
  config: GitHubNotificationConfig,
  verdict: SecurityVerdict,
  findings: Finding[],
  targetUrl: string
): Promise<void> {
  const title = `${ISSUE_TITLE_PREFIX} ${verdict.verdict} — ${targetUrl}`;
  const body = buildReportBody(verdict, findings, targetUrl);

  // Look for an existing open issue with the label
  const searchUrl = `https://api.github.com/repos/${config.repo}/issues?labels=${encodeURIComponent(ISSUE_LABEL)}&state=open&per_page=10`;
  const searchResponse = await ghFetch(searchUrl, config.token, "GET");
  if (!searchResponse.ok) {
    throw new Error(`GitHub issue search failed (${searchResponse.status})`);
  }

  const issues = await searchResponse.json() as Array<{ number: number; title: string }>;
  const existing = issues.find(i => i.title.startsWith(ISSUE_TITLE_PREFIX));

  if (existing) {
    const updateUrl = `https://api.github.com/repos/${config.repo}/issues/${existing.number}`;
    const updateResponse = await ghFetch(updateUrl, config.token, "PATCH", { title, body });
    if (!updateResponse.ok) {
      throw new Error(`GitHub issue update failed (${updateResponse.status})`);
    }
  } else {
    const createUrl = `https://api.github.com/repos/${config.repo}/issues`;
    const createResponse = await ghFetch(createUrl, config.token, "POST", {
      title,
      body,
      labels: [ISSUE_LABEL],
    });
    if (!createResponse.ok) {
      throw new Error(`GitHub issue creation failed (${createResponse.status})`);
    }
  }
}

function buildReportBody(verdict: SecurityVerdict, findings: Finding[], targetUrl: string): string {
  const counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
  for (const f of findings) {
    counts[f.severity] = (counts[f.severity] ?? 0) + 1;
  }

  const icon = { SAFE: "✅", UNSAFE: "⛔", REVIEW_REQUIRED: "⚠️", INCONCLUSIVE: "❓" }[verdict.verdict] ?? "❓";

  const lines = [
    `## ${icon} Breach Gate Security Report — ${verdict.verdict}`,
    ``,
    `**Target:** \`${targetUrl}\``,
    `**Verdict:** ${verdict.verdict}`,
    `**Reason:** ${verdict.reason}`,
    ``,
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${counts.CRITICAL} |`,
    `| High     | ${counts.HIGH} |`,
    `| Medium   | ${counts.MEDIUM} |`,
    `| Low      | ${counts.LOW} |`,
  ];

  if (verdict.confirmedExploits.length > 0) {
    lines.push(``, `**Confirmed Exploits:** ${verdict.confirmedExploits.length}`);
    for (const exploit of verdict.confirmedExploits.slice(0, 5)) {
      lines.push(`- ${exploit.title} (${exploit.severity})`);
    }
  }

  lines.push(``, `*Generated by [Breach Gate](https://github.com/breach-gate/breach-gate)*`);
  return lines.join("\n");
}

async function ghFetch(
  url: string,
  token: string,
  method: string,
  body?: unknown
): Promise<Response> {
  return fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
}
